#ifndef __S2_NEC_NP_PA600X_ENGINE_H__
#define __S2_NEC_NP_PA600X_ENGINE_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_NEC_NP_PA600X_Engine_BRIGHTNESS_DIG_DIG_INPUT 0
#define __S2_NEC_NP_PA600X_Engine_CONTRAST_DIG_DIG_INPUT 1
#define __S2_NEC_NP_PA600X_Engine_COLOR_DIG_DIG_INPUT 2
#define __S2_NEC_NP_PA600X_Engine_TINT_DIG_DIG_INPUT 3
#define __S2_NEC_NP_PA600X_Engine_SHARPNESS_DIG_DIG_INPUT 4
#define __S2_NEC_NP_PA600X_Engine_VOLUME_DIG_DIG_INPUT 5
#define __S2_NEC_NP_PA600X_Engine_BASS_DIG_DIG_INPUT 6
#define __S2_NEC_NP_PA600X_Engine_TREBLE_DIG_DIG_INPUT 7


/*
* ANALOG_INPUT
*/
#define __S2_NEC_NP_PA600X_Engine_VOLUME_ANALOG_INPUT 0
#define __S2_NEC_NP_PA600X_Engine_BRIGHTNESS_ANALOG_INPUT 1
#define __S2_NEC_NP_PA600X_Engine_CONTRAST_ANALOG_INPUT 2
#define __S2_NEC_NP_PA600X_Engine_COLOR_ANALOG_INPUT 3
#define __S2_NEC_NP_PA600X_Engine_TINT_ANALOG_INPUT 4
#define __S2_NEC_NP_PA600X_Engine_SHARPNESS_ANALOG_INPUT 5
#define __S2_NEC_NP_PA600X_Engine_BASS_ANALOG_INPUT 6
#define __S2_NEC_NP_PA600X_Engine_TREBLE_ANALOG_INPUT 7
#define __S2_NEC_NP_PA600X_Engine_BALANCE_ANALOG_INPUT 8


#define __S2_NEC_NP_PA600X_Engine_FROM_NEC_PA600X_BUFFER_INPUT 9
#define __S2_NEC_NP_PA600X_Engine_FROM_NEC_PA600X_BUFFER_MAX_LEN 200
CREATE_STRING_STRUCT( S2_NEC_NP_PA600X_Engine, __FROM_NEC_PA600X, __S2_NEC_NP_PA600X_Engine_FROM_NEC_PA600X_BUFFER_MAX_LEN );


/*
* DIGITAL_OUTPUT
*/


/*
* ANALOG_OUTPUT
*/
#define __S2_NEC_NP_PA600X_Engine_LAMP_HOURS_ANALOG_OUTPUT 0
#define __S2_NEC_NP_PA600X_Engine_BRIGHTNESS_VALUE_ANALOG_OUTPUT 1
#define __S2_NEC_NP_PA600X_Engine_CONTRAST_VALUE_ANALOG_OUTPUT 2
#define __S2_NEC_NP_PA600X_Engine_COLOR_VALUE_ANALOG_OUTPUT 3
#define __S2_NEC_NP_PA600X_Engine_TINT_VALUE_ANALOG_OUTPUT 4
#define __S2_NEC_NP_PA600X_Engine_SHARPNESS_VALUE_ANALOG_OUTPUT 5
#define __S2_NEC_NP_PA600X_Engine_VOLUME_VALUE_ANALOG_OUTPUT 6
#define __S2_NEC_NP_PA600X_Engine_BASS_VALUE_ANALOG_OUTPUT 7
#define __S2_NEC_NP_PA600X_Engine_TREBLE_VALUE_ANALOG_OUTPUT 8

#define __S2_NEC_NP_PA600X_Engine_TO_NEC_PA600X_STRING_OUTPUT 9


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_NEC_NP_PA600X_Engine )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_STRING_STRUCT( S2_NEC_NP_PA600X_Engine, __FROM_NEC_PA600X );
};

START_NVRAM_VAR_STRUCT( S2_NEC_NP_PA600X_Engine )
{
};



#endif //__S2_NEC_NP_PA600X_ENGINE_H__

